# Generated by Django 4.2.9 on 2024-01-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_articulo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
