# Generated by Django 4.2.9 on 2024-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAventura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos_alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alimento', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos_hidratación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_articulo', models.CharField(max_length=3)),
                ('marca', models.CharField(max_length=3)),
                ('litros', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulos_camping',
        ),
    ]
